/*
 * Capitales des États présents dans le quiz.
 * Références pour les noms français et les capitales :
 * - Nations Unies, UNTERM (Country names and capitals): https://unterm.un.org/unterm2/en/
 * - REST Countries v3.1 (champ capital, données recoupées): https://restcountries.com/
 * - Liste des capitales nationales : https://en.wikipedia.org/wiki/List_of_national_capitals
 * Les pays à plusieurs capitales utilisent la capitale administrative
 * couramment attendue; les variantes admises sont définies dans CAPITAL_ALIASES.
 */
export const CAPITALS = {
"Afrique du Sud":"Pretoria","Algérie":"Alger","Angola":"Luanda","Bénin":"Porto-Novo","Botswana":"Gaborone","Burkina Faso":"Ouagadougou","Burundi":"Gitega","Cameroun":"Yaoundé","Cap-Vert":"Praia","République centrafricaine":"Bangui","Comores":"Moroni","Congo":"Brazzaville","République démocratique du Congo":"Kinshasa","Côte d'Ivoire":"Yamoussoukro","Djibouti":"Djibouti","Égypte":"Le Caire","Érythrée":"Asmara","Éthiopie":"Addis-Abeba","Gabon":"Libreville","Gambie":"Banjul","Ghana":"Accra","Guinée":"Conakry","Guinée-Bissau":"Bissau","Guinée équatoriale":"Ciudad de la Paz","Kenya":"Nairobi","Lesotho":"Maseru","Liberia":"Monrovia","Libye":"Tripoli","Madagascar":"Antananarivo","Malawi":"Lilongwe","Mali":"Bamako","Maroc":"Rabat","Maurice":"Port-Louis","Mauritanie":"Nouakchott","Mozambique":"Maputo","Namibie":"Windhoek","Niger":"Niamey","Nigeria":"Abuja","Ouganda":"Kampala","Rwanda":"Kigali","Sao Tomé-et-Principe":"São Tomé","Sénégal":"Dakar","Seychelles":"Victoria","Sierra Leone":"Freetown","Somalie":"Mogadiscio","Soudan":"Khartoum","Soudan du Sud":"Djouba","Swaziland":"Mbabane","Tanzanie":"Dodoma","Tchad":"N'Djaména","Togo":"Lomé","Tunisie":"Tunis","Zambie":"Lusaka","Zimbabwe":"Harare",
"Antigua-et-Barbuda":"Saint John's","Argentine":"Buenos Aires","Bahamas":"Nassau","Barbade":"Bridgetown","Belize":"Belmopan","Bolivie":"Sucre","Brésil":"Brasília","Canada":"Ottawa","Chili":"Santiago","Colombie":"Bogota","Costa Rica":"San José","Cuba":"La Havane","République dominicaine":"Saint-Domingue","Dominique":"Roseau","Équateur":"Quito","États-Unis":"Washington","Grenade":"Saint-Georges","Guatemala":"Guatemala","Guyana":"Georgetown","Haïti":"Port-au-Prince","Honduras":"Tegucigalpa","Jamaïque":"Kingston","Mexique":"Mexico","Nicaragua":"Managua","Panama":"Panama","Paraguay":"Asunción","Pérou":"Lima","Saint-Christophe-et-Niévès":"Basseterre","Sainte-Lucie":"Castries","Saint-Vincent-et-les Grenadines":"Kingstown","Salvador":"San Salvador","Suriname":"Paramaribo","Trinité-et-Tobago":"Port-d'Espagne","Uruguay":"Montevideo","Venezuela":"Caracas",
"Afghanistan":"Kaboul","Arabie saoudite":"Riyad","Bahreïn":"Manama","Bangladesh":"Dacca","Bhoutan":"Thimphou","Birmanie":"Naypyidaw","Brunei":"Bandar Seri Begawan","Cambodge":"Phnom Penh","Chine":"Pékin","Corée du Nord":"Pyongyang","Corée du Sud":"Séoul","Émirats arabes unis":"Abou Dabi","Inde":"New Delhi","Indonésie":"Jakarta","Irak":"Bagdad","Iran":"Téhéran","Israël":"Jérusalem","Japon":"Tokyo","Jordanie":"Amman","Kazakhstan":"Astana","Kirghizistan":"Bichkek","Koweït":"Koweït","Laos":"Vientiane","Liban":"Beyrouth","Malaisie":"Kuala Lumpur","Maldives":"Malé","Mongolie":"Oulan-Bator","Népal":"Katmandou","Oman":"Mascate","Ouzbékistan":"Tachkent","Pakistan":"Islamabad","Philippines":"Manille","Qatar":"Doha","Singapour":"Singapour","Sri Lanka":"Sri Jayawardenepura Kotte","Syrie":"Damas","Tadjikistan":"Douchanbé","Taïwan":"Taipei","Thaïlande":"Bangkok","Timor oriental":"Dili","Turkménistan":"Achgabat","Turquie":"Ankara","Viêt Nam":"Hanoï","Yémen":"Sanaa",
"Albanie":"Tirana","Allemagne":"Berlin","Andorre":"Andorre-la-Vieille","Arménie":"Erevan","Autriche":"Vienne","Azerbaïdjan":"Bakou","Belgique":"Bruxelles","Biélorussie":"Minsk","Bosnie-Herzégovine":"Sarajevo","Bulgarie":"Sofia","Chypre":"Nicosie","Croatie":"Zagreb","Danemark":"Copenhague","Espagne":"Madrid","Estonie":"Tallinn","Finlande":"Helsinki","France":"Paris","Géorgie":"Tbilissi","Grèce":"Athènes","Hongrie":"Budapest","Irlande":"Dublin","Islande":"Reykjavik","Italie":"Rome","Lettonie":"Riga","Liechtenstein":"Vaduz","Lituanie":"Vilnius","Luxembourg":"Luxembourg","Macédoine du Nord":"Skopje","Malte":"La Valette","Moldavie":"Chișinău","Monaco":"Monaco","Monténégro":"Podgorica","Norvège":"Oslo","Pays-Bas":"Amsterdam","Pologne":"Varsovie","Portugal":"Lisbonne","République tchèque":"Prague","Roumanie":"Bucarest","Royaume-Uni":"Londres","Russie":"Moscou","Saint-Marin":"Saint-Marin","Serbie":"Belgrade","Slovaquie":"Bratislava","Slovénie":"Ljubljana","Suède":"Stockholm","Suisse":"Berne","Ukraine":"Kyiv","Vatican":"Vatican",
"Australie":"Canberra","Fidji":"Suva","Kiribati":"Tarawa-Sud","Marshall":"Majuro","Micronésie":"Palikir","Nauru":"Yaren","Nouvelle-Zélande":"Wellington","Palaos":"Ngerulmud","Papouasie-Nouvelle-Guinée":"Port Moresby","Salomon":"Honiara","Samoa":"Apia","Tonga":"Nuku'alofa","Tuvalu":"Funafuti","Vanuatu":"Port-Vila"
};
export const CAPITAL_ALIASES = {"Pretoria":["Le Cap","Bloemfontein"],"Sucre":["La Paz"],"Sri Jayawardenepura Kotte":["Colombo","Sri Jayawardenapura Kotte"],"Mbabane":["Lobamba"],"Yaren":["District de Yaren"],"Kyiv":["Kiev"],"Dacca":["Dhaka"],"Thimphou":["Thimphu"],"Djouba":["Juba"],"Bogota":["Bogotá"],"Sanaa":["Sana'a"],"Chișinău":["Chisinau"],"Tarawa-Sud":["Tarawa"]};
